package com.sumhr.api.error;

public enum CustomErrorType {

    FIELD_ERROR, LOGICAL_ERROR, NOT_IMPLEMENTED_ERROR, DATA_INTEGRITY_ERROR, NOT_FOUND_ERROR, SERVER_ERROR, RANGE_ERROR, ACCESS_CONTROL_ERROR

}
